config/routes.rb
Rails.application.routes.draw do
  root "games#new"
  get 'games/new'
  post 'games/score'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new
    @letters = ("A".."Z").to_a.sample(10)
  end

  def score
    @letters = params[:letters].split
    @word = params[:word].upcase

    @included = @word.chars.all? do |letter|
      @word.count(letter) <= @letters.count(letter)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/new.html.erb
<h1>WELCOME!</h1>


</ul>
  <% @letters.each do |letter| %>
    <div class="p-5">
     <%= letter %>
    </div>
  <% end %>
<ul>

<form action="/games/score" method="POST" data-turbo="false">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <%= hidden_field_tag :letters, @letters %>
  <div class="input-group">
    <input type="text" name="word" class="form-control">
    <input type="submit" value="Play" class="btn btn-primary">
  </div>
</form>

app/views/games/score.html.erb
<h1>Here is your score</h1>
<p>What's the longest word you can make?</p>

<div class="d-flex">
  <% @letters.each do |letter| %>
    <div class="p-5">
      <%= letter %>
    </div>
  <% end %>
</div>

<h1> Your word: <%= @word %></h1>

<% if @included %>
  <h1>Good Job!!</h1>
<% else %>
  <h1>Try Again!!</h1>
<% end %>

<%= link_to "Play Again!", games_new_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>